MONGODB_USERNAME = 'TWITTER_TOKEN_MONGODB_USERNAME'
MONGODB_PASSWORD = 'TWITTER_TOKEN_MONGODB_PASSWORD'

MONGODB_HOST = 'TWITTER_TOKEN_MONGODB_HOST'
MONGODB_PORT = 'TWITTER_TOKEN_MONGODB_PORT'

MONGODB_DATABASE = 'TWITTER_TOKEN_MONGODB_DATABASE'
MONGODB_COLLECTION = 'TWITTER_TOKEN_MONGODB_COLLECTION'

MONGODB_OPTIONS_ = 'TWITTER_TOKEN_MONGODB_OPTIONS_'
